export const soldiersData = [
  {
    id: "001",
    name: "יוסי כהן",
    unit: "גדוד 50",
    rank: "רב-טוראי",
    role: "לוחם",
    status: "בפעילות מבצעית",
    phone: "050-1234567",
    email: "yosi@example.com",
  },
  {
    id: "002",
    name: "דנה לוי",
    unit: "בה\"ד 1",
    rank: "סמל",
    role: "מדריכת חי\"ר",
    status: "בהכשרה",
    phone: "052-9876543",
    email: "dana@example.com",
  },
  {
    id: "003",
    name: "משה דוידוב",
    unit: "גדוד 202",
    rank: "סמל ראשון",
    role: "חובש קרבי",
    status: "בטיפול רפואי",
    phone: "054-4567890",
    email: "moshe@example.com",
  },
  {
    id: "004",
    name: "איילת פרידמן",
    unit: "יחידת דובדבן",
    rank: "רב-טוראית",
    role: "לוחמת",
    status: "בבסיס",
    phone: "053-8765432",
    email: "ayelet@example.com",
  },
  {
    id: "005",
    name: "אורי בן-זקן",
    unit: "סיירת מטכ\"ל",
    rank: "סגן",
    role: "קצין מודיעין",
    status: "בחופשה",
    phone: "055-2345678",
    email: "uri@example.com",
  },
  {
    id: "006",
    name: "נועם שמואלי",
    unit: "חיל האוויר",
    rank: "סרן",
    role: "טייס קרב",
    status: "בגף המבצעי",
    phone: "058-7654321",
    email: "noam@example.com",
  },
  {
    id: "007",
    name: "רונית שמעוני",
    unit: "גדוד 13",
    rank: "סמל ראשון",
    role: "קשרית",
    status: "בתרגיל שטח",
    phone: "050-8765432",
    email: "ronit@example.com",
  },
  {
    id: "008",
    name: "גדי אלון",
    unit: "יחידת 8200",
    rank: "טוראי ראשון",
    role: "אחראי תקשוב",
    status: "בפיתוח תוכנה",
    phone: "050-1234321",
    email: "gadi@example.com",
  },
];



// export const columnsList = [
//   {
//     key: "id",
//     label: "מספר אישי",
//     selectOption: [
//       { id: "1", name: "1234567" },
//       { id: "2", name: "2345678" },
//       { id: "3", name: "3456789" },
//       { id: "4", name: "4567890" },
//     ],
//   },
//   {
//     key: "name",
//     label: "שם חייל",
//     selectOption: [
//       { id: "1", name: "יוסי כהן" },
//       { id: "2", name: "דוד לוי" },
//       { id: "3", name: "שרה לוי" },
//       { id: "4", name: "נועה ישראלי" },
//     ],
//   },
//   {
//     key: "rank",
//     label: "דרגה",
//     selectOption: [
//       { id: "1", name: "סמל" },
//       { id: "2", name: "סמל ראשון" },
//       { id: "3", name: "רב-סמל" },
//       { id: "4", name: "רב-סרן" },
//     ],
//   },
//   {
//     key: "unit",
//     label: "יחידה",
//     selectOption: [
//       { id: "1", name: '8200' },
//       { id: "2", name: "669" },
//       { id: "3", name: "שלדג" },
//       { id: "4", name: "סיירת מטכ'ל" },
//     ],
//   },
//   {
//     key: "role",
//     label: "תפקיד",
//     selectOption: [
//       { id: "1", name: "לוחם" },
//       { id: "2", name: "נהג" },
//       { id: "3", name: "חובש" },
//       { id: "4", name: "קצין מודיעין" },
//     ],
//   },
//   {
//     key: "status",
//     label: "סטטוס שירות",
//     selectOption: [
//       { id: "1", name: "פעיל" },
//       { id: "2", name: "חופשה" },
//       { id: "3", name: "בכוננות" },
//       { id: "4", name: "משוחרר" },
//     ],
//   },
//   {
//     key: "email",
//     label: "אימייל",
//     selectOption: [
//       { id: "1", name: "פעיל" },
//       { id: "2", name: "חופשה" },
//       { id: "3", name: "בכוננות" },
//       { id: "4", name: "משוחרר" },
//     ],
//   },
//   {
//     key: "phone",
//     label: "נייד",
//     selectOption: [
//       { id: "1", name: "פעיל" },
//       { id: "2", name: "חופשה" },
//       { id: "3", name: "בכוננות" },
//       { id: "4", name: "משוחרר" },
//     ],
//   },
//   {
//     key: "note",
//     label: "הערות",
//     selectOption: [
//       { id: "1", name: "מצטיין" },
//       { id: "2", name: "דורש חידוש ציוד" },
//       { id: "3", name: "במעקב רפואי" },
//       { id: "4", name: "מיועד לקורס פיקוד" },
//     ],
//   },
// ];
